// Generated by tools/gen_font_table.py from the families under
// lib/esp32-weather-epd-assets/fonts/. Do not edit: re-run the script
// after adding a family with tools/fontconvert.py.

//
// Names of the compiled-in families, in FONT_FAMILIES order (font_table.h),
// for code that must not pull in the glyph data (settings.cpp, portal.cpp).
#pragma once

static const char *const FONT_FAMILY_NAMES[] = {
#if defined(FONT_INCLUDE_FreeSans) && FONT_INCLUDE_FreeSans
  "FreeSans",
#endif
#if defined(FONT_INCLUDE_Bitter) && FONT_INCLUDE_Bitter
  "Bitter",
#endif
#if defined(FONT_INCLUDE_FreeMono) && FONT_INCLUDE_FreeMono
  "FreeMono",
#endif
#if defined(FONT_INCLUDE_FreeSerif) && FONT_INCLUDE_FreeSerif
  "FreeSerif",
#endif
#if defined(FONT_INCLUDE_Lato_Regular) && FONT_INCLUDE_Lato_Regular
  "Lato_Regular",
#endif
#if defined(FONT_INCLUDE_Montserrat_Regular) && FONT_INCLUDE_Montserrat_Regular
  "Montserrat_Regular",
#endif
#if defined(FONT_INCLUDE_OpenSans_Regular) && FONT_INCLUDE_OpenSans_Regular
  "OpenSans_Regular",
#endif
#if defined(FONT_INCLUDE_Poppins_Regular) && FONT_INCLUDE_Poppins_Regular
  "Poppins_Regular",
#endif
#if defined(FONT_INCLUDE_Quicksand_Regular) && FONT_INCLUDE_Quicksand_Regular
  "Quicksand_Regular",
#endif
#if defined(FONT_INCLUDE_Raleway_Regular) && FONT_INCLUDE_Raleway_Regular
  "Raleway_Regular",
#endif
#if defined(FONT_INCLUDE_RobotoMono_Regular) && FONT_INCLUDE_RobotoMono_Regular
  "RobotoMono_Regular",
#endif
#if defined(FONT_INCLUDE_RobotoSlab_Regular) && FONT_INCLUDE_RobotoSlab_Regular
  "RobotoSlab_Regular",
#endif
#if defined(FONT_INCLUDE_Roboto_Regular) && FONT_INCLUDE_Roboto_Regular
  "Roboto_Regular",
#endif
#if defined(FONT_INCLUDE_UbuntuMono_R) && FONT_INCLUDE_UbuntuMono_R
  "UbuntuMono_R",
#endif
#if defined(FONT_INCLUDE_Ubuntu_R) && FONT_INCLUDE_Ubuntu_R
  "Ubuntu_R",
#endif
};
static const int FONT_FAMILY_NAME_COUNT =
    sizeof(FONT_FAMILY_NAMES) / sizeof(FONT_FAMILY_NAMES[0]);

