# PlatformIO pre-build script: packs the settings page (data/portal.html)
# into the firmware, so that a firmware update installed from the page
# brings the page that belongs to it.
#
# The page used to be served from the flash filesystem, which a firmware
# update does not touch: after every update the device kept its old page,
# and the new one needed a cable (uploadfs, which also wipes the settings).
#
# Writes include/portal_page.h (gitignored): the page, gzip-compressed, as a
# byte array. The file is only rewritten when its content changes, so
# ordinary rebuilds stay incremental.
Import("env")
import gzip
import io
import os

project = env.subst("$PROJECT_DIR")
source = os.path.join(project, "data", "portal.html")
target = os.path.join(project, "include", "portal_page.h")

with open(source, "rb") as f:
    page = f.read()
packed = io.BytesIO()
# mtime=0: the same page always packs to the same bytes
with gzip.GzipFile(fileobj=packed, mode="wb", compresslevel=9, mtime=0) as g:
    g.write(page)
data = packed.getvalue()

rows = []
for i in range(0, len(data), 20):
    rows.append("  " + ",".join("0x%02x" % b for b in data[i:i + 20]) + ",")
content = ("// Generated by scripts/embed_portal.py at build time from "
           "data/portal.html --\n// do not edit or commit.\n"
           "#pragma once\n#include <Arduino.h>\n\n"
           "// data/portal.html, gzip-compressed (%d bytes of page)\n"
           "static const size_t PORTAL_PAGE_LEN = %d;\n"
           "static const uint8_t PORTAL_PAGE[] PROGMEM = {\n%s\n};\n"
           % (len(page), len(data), "\n".join(rows)))
old = open(target).read() if os.path.exists(target) else None
if old != content:
    with open(target, "w", newline="\n") as f:
        f.write(content)
    print("[embed_portal] portal_page.h: %d bytes of page, %d packed"
          % (len(page), len(data)))
