# PlatformIO pre-build script: records which commit the firmware was built
# from, so the portal's "Current firmware build" line and the boot log can
# identify the running build. A compile timestamp alone says when, not what,
# and a rebuilt older commit looks newer than it is.
#
# Writes include/build_rev.h (gitignored) defining GIT_REV as the short hash,
# with a trailing "+" when tracked files had uncommitted changes, or
# "unknown" when git is unavailable (e.g. a zip download). The file is only
# rewritten when its content changes, so ordinary rebuilds stay incremental.
Import("env")
import os
import subprocess

project = env.subst("$PROJECT_DIR")   # git searches upward from here


def git(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=project,
                                       stderr=subprocess.DEVNULL,
                                       text=True).strip()
    except Exception:
        return ""


rev = git("rev-parse", "--short=8", "HEAD") or "unknown"
if rev != "unknown" and git("status", "--porcelain", "--untracked-files=no"):
    rev += "+"

content = ("// Generated by scripts/git_rev.py at build time -- "
           "do not edit or commit.\n"
           "#pragma once\n"
           '#define GIT_REV "%s"\n' % rev)
path = os.path.join(project, "include", "build_rev.h")
old = open(path).read() if os.path.exists(path) else None
if old != content:
    with open(path, "w", newline="\n") as f:
        f.write(content)
    print("[git_rev] build_rev.h -> " + rev)
