#!/usr/bin/env python3
"""Generate the runtime font table for esp32-weather-epd.

Scans platformio/src and include for the FONT_<size>pt8b names the code
actually uses, then lib/esp32-weather-epd-assets/fonts/<Family>/ for families
that provide every one of those faces (tools/fontconvert.py generates all of
them), and writes two headers next to the families:

  fonts/font_table.h  -- includes every family whose FONT_INCLUDE_<Family>
                         macro is set (config.h), a table of their faces, and
                         the FONT_*pt8b names the renderer uses, resolved at
                         runtime through FONT_FAMILY_INDEX (sizes from
                         SMALL_BELOW_PT up) and FONT_SMALL_FAMILY_INDEX (the
                         smaller labels, axis text and tags)
  fonts/font_names.h  -- the same families' names only, for settings.cpp and
                         the portal, so they need not pull in the glyph data

Only the sizes in use go into the table, and each one is guarded by the
preprocessor conditions around its uses (a size drawn only on the DISP_BW_V1
panel, say, stays out of every other build), so the linker still drops what
a given build never draws: a table referencing all 17 faces of a family
would cost ~90 KB of flash per family for glyphs nothing draws. FreeSans is
listed first (the historical default); the rest alphabetically. Run this
after adding or removing a family, or after the renderer starts using a new
size (an unknown FONT_ name then fails to compile, which is the reminder).
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.normpath(os.path.join(HERE, "..", "platformio", "lib",
                                         "esp32-weather-epd-assets", "fonts"))
SRC_DIRS = [os.path.normpath(os.path.join(HERE, "..", "platformio", d))
            for d in ("src", "include")]
# Faces below this point size are drawn in the small-text family (config.json
# "font_small": widget labels, graph axis, source tags); this size and up in
# the main family (forecast day names, widget values, the header, the big
# temperature). 1-bit text this small favours even sans-serif strokes.
SMALL_BELOW_PT = 11
HEADER = ("// Generated by tools/gen_font_table.py from the families under\n"
          "// lib/esp32-weather-epd-assets/fonts/. Do not edit: re-run the script\n"
          "// after adding a family with tools/fontconvert.py.\n")
NAME_RE = re.compile(r"FONT_([0-9]+pt8b(?:_temperature)?)(?![A-Za-z0-9_])")
DIRECTIVE_RE = re.compile(r"(ifdef|ifndef|if|elif|else|endif)(?![A-Za-z0-9_])[ ]*(.*)")


def strip_comment(expr):
    expr = expr.split("//")[0]
    expr = re.sub(r"/[*].*?[*]/", "", expr)
    return expr.strip()


def level_condition(level):
    """C expression for being inside the current branch of one #if level."""
    current, previous = level
    parts = []
    if previous:
        parts.append("!(" + " || ".join(previous) + ")")
    if current is not None:
        parts.append(current)
    return " && ".join(parts)


def scan_uses():
    """Map each FONT_ name to the set of preprocessor conditions (one C
    expression per use site, "" for an unconditional use) under which the
    firmware references it."""
    uses = {}
    for d in SRC_DIRS:
        for root, _, files in os.walk(d):
            for fn in files:
                if not fn.endswith((".cpp", ".h", ".inc")) or fn == "font_table.h":
                    continue
                stack = []  # per #if level: [current branch cond, [earlier branch conds]]
                with open(os.path.join(root, fn), encoding="utf-8",
                          errors="replace") as f:
                    for line in f:
                        s = line.strip()
                        if s.startswith("#"):
                            m = DIRECTIVE_RE.match(s[1:].strip())
                            if m:
                                kw, expr = m.group(1), strip_comment(m.group(2))
                                if kw == "ifdef":
                                    stack.append(["defined(%s)" % expr, []])
                                elif kw == "ifndef":
                                    stack.append(["!defined(%s)" % expr, []])
                                elif kw == "if":
                                    stack.append(["(%s)" % expr, []])
                                elif kw == "elif":
                                    stack[-1][1].append(stack[-1][0])
                                    stack[-1][0] = "(%s)" % expr
                                elif kw == "else":
                                    stack[-1][1].append(stack[-1][0])
                                    stack[-1][0] = None
                                elif kw == "endif":
                                    stack.pop()
                                continue
                        for name in NAME_RE.findall(line):
                            cond = " && ".join(c for c in map(level_condition, stack) if c)
                            uses.setdefault(name, set()).add(cond)
    return uses


USES = scan_uses()
NAMES = sorted(USES, key=lambda n: (n.endswith("_temperature"),
                                    int(n.split("pt")[0])))
if not NAMES:
    raise SystemExit("no FONT_*pt8b names found under " + ", ".join(SRC_DIRS))


def guard_condition(name):
    """None when some use is unconditional, else the OR of the use conditions."""
    conds = USES[name]
    if "" in conds:
        return None
    return " || ".join("(%s)" % c for c in sorted(conds))


def family_index(name):
    """Which runtime index resolves this face: the main or the small family."""
    if name.endswith("_temperature") or int(name.split("pt")[0]) >= SMALL_BELOW_PT:
        return "FONT_FAMILY_INDEX"
    return "FONT_SMALL_FAMILY_INDEX"


def complete(fam):
    return all(os.path.exists(os.path.join(FONT_DIR, fam, "%s_%s.h" % (fam, n)))
               for n in NAMES)


fams = sorted(d for d in os.listdir(FONT_DIR)
              if os.path.isdir(os.path.join(FONT_DIR, d)) and complete(d))
if "FreeSans" in fams:
    fams.remove("FreeSans")
    fams.insert(0, "FreeSans")


def family_guard(fam):
    return "#if defined(FONT_INCLUDE_%s) && FONT_INCLUDE_%s" % (fam, fam)


out = [HEADER,
       "//",
       "// Every family whose FONT_INCLUDE_<Family> macro is set (config.h) is",
       "// compiled in and selectable at runtime: FONT_FAMILY_INDEX (config.json",
       "// \"font\") for faces of FONT_SMALL_BELOW_PT and up, FONT_SMALL_FAMILY_INDEX",
       "// (\"font_small\") for the smaller labels, axis text and tags. Each family",
       "// costs roughly 150-250 KB of flash. The FONT_*pt8b names used throughout",
       "// the renderer resolve to the right family's face of that size.",
       "//",
       "// A face is only referenced (and so only linked) when this build can draw",
       "// it: FONT_TABLE_HAS_<size> mirrors the preprocessor conditions around the",
       "// uses of FONT_<size> in the sources.",
       "#pragma once", "",
       "#define FONT_SMALL_BELOW_PT %d" % SMALL_BELOW_PT, ""]
for n in NAMES:
    cond = guard_condition(n)
    if cond is None:
        out.append("#define FONT_TABLE_HAS_%s 1" % n)
    else:
        out.append("#if %s" % cond)
        out.append("  #define FONT_TABLE_HAS_%s 1" % n)
        out.append("#else")
        out.append("  #define FONT_TABLE_HAS_%s 0" % n)
        out.append("#endif")
out.append("")
for fam in fams:
    out.append(family_guard(fam))
    for n in NAMES:
        if guard_condition(n) is not None:
            out.append("#if FONT_TABLE_HAS_%s" % n)
            out.append('  #include "%s/%s_%s.h"' % (fam, fam, n))
            out.append("#endif")
        else:
            out.append('#include "%s/%s_%s.h"' % (fam, fam, n))
    out.append("#endif")
    out.append("")
out.append("// one slot per face in use; nullptr where this build never draws it")
for n in NAMES:
    if guard_condition(n) is not None:
        out.append("#if FONT_TABLE_HAS_%s" % n)
        out.append("  #define FONT_FACE_%s(F) &F##_%s" % (n, n))
        out.append("#else")
        out.append("  #define FONT_FACE_%s(F) nullptr" % n)
        out.append("#endif")
    else:
        out.append("#define FONT_FACE_%s(F) &F##_%s" % (n, n))
out += ["",
        "struct font_family_t",
        "{",
        "  const char *name;",
        "  // " + " ".join(NAMES),
        "  const GFXfont *const size[%d];" % len(NAMES),
        "};",
        "",
        "static const font_family_t FONT_FAMILIES[] = {"]
for fam in fams:
    out.append(family_guard(fam))
    faces = ", ".join("FONT_FACE_%s(%s)" % (n, fam) for n in NAMES)
    out.append('  {"%s", {%s}},' % (fam, faces))
    out.append("#endif")
out += ["};",
        "static const int FONT_FAMILY_COUNT =",
        "    sizeof(FONT_FAMILIES) / sizeof(FONT_FAMILIES[0]);",
        'static_assert(sizeof(FONT_FAMILIES) > 0,',
        '              "enable at least one FONT_INCLUDE_<Family> in config.h");',
        ""]
for i, n in enumerate(NAMES):
    out.append("#define FONT_%-20s (*FONT_FAMILIES[%s].size[%d])"
               % (n, family_index(n), i))
with open(os.path.join(FONT_DIR, "font_table.h"), "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")

out = [HEADER,
       "//",
       "// Names of the compiled-in families, in FONT_FAMILIES order (font_table.h),",
       "// for code that must not pull in the glyph data (settings.cpp, portal.cpp).",
       "#pragma once", "",
       "static const char *const FONT_FAMILY_NAMES[] = {"]
for fam in fams:
    out.append(family_guard(fam))
    out.append('  "%s",' % fam)
    out.append("#endif")
out += ["};",
        "static const int FONT_FAMILY_NAME_COUNT =",
        "    sizeof(FONT_FAMILY_NAMES) / sizeof(FONT_FAMILY_NAMES[0]);", ""]
with open(os.path.join(FONT_DIR, "font_names.h"), "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")

for n in NAMES:
    cond = guard_condition(n)
    print("%-22s %-24s %s" % (n, family_index(n), "always" if cond is None else cond))
print("families:", ", ".join(fams))
print("wrote", os.path.join(FONT_DIR, "font_table.h"), "and font_names.h")
