#!/usr/bin/env python3
"""Generate the assets of the 1600x1200 layout (GDEB0709E01, 282 ppi):

  assets709/fonts709.h   every face the layout draws, at its pixel size
  assets709/icons709.h   condition icons at 220 and 104 px
  assets709/moon709.h    the moon at 32 phases, from NASA's lunar map

Fonts
  The 800x480 layouts size their type in points through Adafruit GFX fonts.
  GFXglyph keeps a glyph's size and offsets in 8 bits, which a 190 px numeral
  overflows, so this layout has a format of its own (Font709, see the header
  it writes) with 16-bit fields and the face's ascent and descent alongside,
  which the anchored text routine needs. Characters are 0x20-0xFF as in the
  other families; 0x7F carries the en dash, which Latin-1 has no place for.

Icons
  The artwork is the Google weather set the 800x480 colour panels use
  (tools/google_icons/, downloaded by generate_final_icons.py, never
  committed). What changes is its translation into ink. Shrinking the
  picture and letting error diffusion sort every pixel into an ink is what
  makes clouds and suns grainy; here each part of the picture is recognised
  (sun, cloud, rain, moon, lightning) and given a recipe of its own: flat
  colour becomes one solid ink (the sun, a screen of red in yellow: yellow
  alone is too pale on the panel), greys become a regular screen of dots, edges
  are cut clean at the final size, and pale shapes get a hairline outline so
  clouds can stay light without dissolving into the paper.

Moon
  NASA's LRO colour map (tools/moon709/lroc_color_poles_1k.jpg, public
  domain, svs.gsfc.nasa.gov/4720) wrapped on a sphere and lit from the side
  for each phase. The unlit side is black.

Usage: python tools/gen_assets709.py [fonts] [icons] [moon]
       (no argument = all three)

    pip install freetype-py fonttools pillow numpy
"""
import math
import os
import sys
import tempfile

import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
TTF = os.path.join(HERE, "..", "fonts", "ttf")
OUT = os.path.join(HERE, "..", "platformio", "lib", "esp32-weather-epd-assets", "assets709")
NOTE = "// Generated by tools/gen_assets709.py -- do not edit.\n"

# ---------------------------------------------------------------- fonts
FIRST, LAST = 0x20, 0xFF
EN_DASH_SLOT = 0x7F
DIGITS = "0123456789.-" + chr(0xB0)
# (name, face, pixel size, subset or None, auto-hint)
FACES = [("BITTER_190D", "bitter", 190, DIGITS, False),
         ("BITTER_150D", "bitter", 150, DIGITS, False),   # when 190 is too wide: 100, -12
         ("BITTER_62D", "bitter", 62, DIGITS, False),
         ("BITTER_42D", "bitter", 42, DIGITS, True),
         ("BITTERSB_72", "bittersb", 72, None, False)]
FACES += [("BITTER_%d" % s, "bitter", s, None, s <= 40) for s in (52, 40, 36, 34, 32, 30, 27, 24, 22)]
FACES += [("SANS_%d" % s, "sans", s, None, False) for s in (38, 32, 30, 28, 27, 26, 25, 24, 23, 22)]
FACES += [("SANSB_25", "sansb", 25, None, False)]


def face_files():
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer
    semibold = os.path.join(tempfile.gettempdir(), "Bitter-wght600.ttf")
    var = TTFont(os.path.join(TTF, "Bitter-var.ttf"))
    instancer.instantiateVariableFont(var, {"wght": 600}).save(semibold)
    return {"bitter": os.path.join(TTF, "Bitter-Regular.ttf"), "bittersb": semibold,
            "sans": os.path.join(TTF, "FreeSans.otf"), "sansb": os.path.join(TTF, "FreeSansBold.ttf")}


def render_face(path, px, only, autohint):
    import freetype
    face = freetype.Face(path)
    face.set_pixel_sizes(0, px)
    flags = freetype.FT_LOAD_TARGET_MONO
    if autohint:
        flags |= freetype.FT_LOAD_FORCE_AUTOHINT
    bitmaps, glyphs = bytearray(), []
    face.load_glyph(0, flags)
    blank = face.glyph.advance.x >> 6
    for code in range(FIRST, LAST + 1):
        ch = 0x2013 if code == EN_DASH_SLOT else code
        if only is not None and chr(code) not in only:
            glyphs.append((len(bitmaps), 0, 0, blank, 0, 0))
            continue
        face.load_char(ch, flags)
        face.glyph.render(freetype.FT_RENDER_MODE_MONO)
        g = face.glyph
        bm = g.bitmap
        off = len(bitmaps)
        acc, mask = 0, 0x80
        for y in range(bm.rows):
            row = y * bm.pitch
            for x in range(bm.width):
                if bm.buffer[row + (x >> 3)] & (0x80 >> (x & 7)):
                    acc |= mask
                mask >>= 1
                if mask == 0:
                    bitmaps.append(acc)
                    acc, mask = 0, 0x80
        if mask != 0x80:
            bitmaps.append(acc)
        glyphs.append((off, bm.width, bm.rows, g.advance.x >> 6, g.bitmap_left, -g.bitmap_top))
    m = face.size
    ascent = (m.ascender + 32) >> 6
    descent = (abs(m.descender) + 32) >> 6
    return bytes(bitmaps), glyphs, ascent, descent, m.height >> 6


def write_fonts():
    files = face_files()
    total = 0
    with open(os.path.join(OUT, "fonts709.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write(NOTE)
        f.write("// Bitter: SIL Open Font License 1.1. FreeSans: GNU FreeFont, GPL v3 with the\n"
                "// font exception. Glyph bitmaps are 1 bit per pixel, MSB first, each glyph\n"
                "// padded to a whole byte. yOff is measured from the baseline (negative = up).\n"
                "#ifndef __FONTS709_H__\n#define __FONTS709_H__\n\n#include <Arduino.h>\n\n"
                "struct Glyph709 { uint32_t offset; uint16_t w, h; int16_t xAdv, xOff, yOff; };\n"
                "struct Font709\n{\n  const uint8_t *bitmaps;\n  const Glyph709 *glyphs;\n"
                "  uint8_t first, last;\n  int16_t ascent, descent, yAdvance;\n};\n\n")
        for name, key, px, only, hint in FACES:
            bitmaps, glyphs, asc, desc, yadv = render_face(files[key], px, only, hint)
            f.write("static const uint8_t F709_%s_BITS[] PROGMEM = {\n" % name)
            for i in range(0, len(bitmaps), 16):
                f.write("  " + ",".join("0x%02X" % b for b in bitmaps[i:i + 16]) + ",\n")
            f.write("};\nstatic const Glyph709 F709_%s_GLYPHS[] PROGMEM = {\n" % name)
            for g in glyphs:
                f.write("  {%d,%d,%d,%d,%d,%d},\n" % g)
            f.write("};\nstatic const Font709 F_%s PROGMEM = {F709_%s_BITS, F709_%s_GLYPHS, "
                    "0x%02X, 0x%02X, %d, %d, %d};\n\n" % (name, name, name, FIRST, LAST, asc, desc, yadv))
            size = len(bitmaps) + len(glyphs) * 14
            total += size
            print("  %-14s %3d px  ascent %3d  descent %3d  %7d bytes" % (name, px, asc, desc, size))
        f.write("#endif\n")
    print("fonts709.h: %d faces, %.0f KB of flash" % (len(FACES), total / 1024))


# ---------------------------------------------------------------- icons
BLACK, WHITE, RED, YELLOW, GREEN, BLUE = 1, 2, 3, 4, 5, 6   # as icons_color.h
ICON_SIZES = [220, 104]
BAYER = np.array([[0, 32, 8, 40, 2, 34, 10, 42], [48, 16, 56, 24, 50, 18, 58, 26],
                  [12, 44, 4, 36, 14, 46, 6, 38], [60, 28, 52, 20, 62, 30, 54, 22],
                  [3, 35, 11, 43, 1, 33, 9, 41], [51, 19, 59, 27, 49, 17, 57, 25],
                  [15, 47, 7, 39, 13, 45, 5, 37], [63, 31, 55, 23, 61, 29, 53, 21]],
                 dtype=np.float32) / 64.0 + 1 / 128.0
# Yellow ink alone is too close to the paper to read as a sun: on the
# panel it is a pale mustard. The E1002's icons, which do read, carry
# about one red dot in five among the yellow (measured in icons_color.h:
# 18 to 20%), so the sun gets the same share here, as a regular screen.
SUN_RED = 0.19
# cloud greys, lightest lobe to deepest shadow, as the share of black dots
CLOUD = (0.06, 0.16, 0.26, 0.48)


def _erode(mask, n):
    im = Image.fromarray((mask * 255).astype(np.uint8), "L")
    for _ in range(n):
        im = im.filter(ImageFilter.MinFilter(3))
    return np.asarray(im) > 127


def _dilate(mask, n):
    im = Image.fromarray((mask * 255).astype(np.uint8), "L")
    for _ in range(n):
        im = im.filter(ImageFilter.MaxFilter(3))
    return np.asarray(im) > 127


def rework(path, size):
    """Ink indices (0 = nothing drawn), size x size."""
    name = os.path.basename(path)
    im = Image.open(path).convert("RGBA").convert("RGBa").resize((size, size), Image.LANCZOS)
    a = np.asarray(im.convert("RGBA"), dtype=np.float32) / 255.0
    r, g, b, alpha = a[..., 0], a[..., 1], a[..., 2], a[..., 3]
    mx, mn = a[..., :3].max(axis=2), a[..., :3].min(axis=2)
    v = mx
    s = np.where(mx > 0, (mx - mn) / np.maximum(mx, 1e-6), 0)
    d = np.maximum(mx - mn, 1e-6)
    hue = np.zeros_like(v)
    hue = np.where(mx == r, ((g - b) / d) % 6, hue)
    hue = np.where(mx == g, (b - r) / d + 2, hue)
    hue = np.where(mx == b, (r - g) / d + 4, hue)
    hue = hue * 60
    lum = 0.299 * r + 0.587 * g + 0.114 * b

    solid = alpha >= 0.5
    warm = solid & (s > 0.28) & (hue >= 15) & (hue <= 70)
    bolt = warm & (hue < 40)
    sun = warm & ~bolt
    rain = solid & (s > 0.45) & (hue >= 165) & (hue <= 205)
    moon = solid & ~rain & (s > 0.07) & (hue > 205) & (hue < 250)
    grey = solid & ~warm & ~rain & ~moon
    snow = grey & (v < 0.80) & ("snow" in name)

    yy, xx = np.mgrid[0:size, 0:size]
    th = BAYER[yy % 8, xx % 8]
    out = np.zeros((size, size), dtype=np.uint8)
    dens = np.interp(v, [0.62, 0.78, 0.86, 0.905, 0.945], [0.62, CLOUD[3], CLOUD[2], CLOUD[1], CLOUD[0]])
    out[grey] = np.where(dens > th, BLACK, WHITE)[grey]
    mdens = np.interp(s, [0.10, 0.22, 0.34], [0.20, 0.30, 0.46])
    out[moon] = np.where(mdens > th, BLUE, WHITE)[moon]
    shade = np.clip((0.80 - lum) / 0.22, 0, 1) * 0.38
    out[sun] = np.where(SUN_RED + shade * (1 - SUN_RED) > th, RED, YELLOW)[sun]
    out[bolt] = np.where(0.42 > th, RED, YELLOW)[bolt]
    out[rain] = BLUE
    out[snow] = BLUE
    w = max(1, int(round(size / 95.0)))
    pale = grey | moon
    edge = pale & ~_erode(solid, w)
    edge |= pale & _dilate(sun | bolt, w)
    out[edge & ~snow] = BLACK
    return out


def pack4(idx):
    flat = idx.reshape(-1).tolist()
    if len(flat) & 1:
        flat.append(0)
    return bytes((flat[i] << 4) | flat[i + 1] for i in range(0, len(flat), 2))


def emit_bytes(f, name, data):
    f.write("static const uint8_t %s[%d] PROGMEM = {\n" % (name, len(data)))
    for i in range(0, len(data), 20):
        f.write("  " + ",".join("0x%02X" % b for b in data[i:i + 20]) + ",\n")
    f.write("};\n")


def write_icons():
    import generate_google_preview as gpre
    src = os.path.join(HERE, "google_icons")
    total = 0
    with open(os.path.join(OUT, "icons709.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write(NOTE)
        f.write("// Condition icons, 4 bits per pixel, two pixels per byte (high nibble first),\n"
                "// row-major. 0 = nothing drawn, 1 black, 2 white, 3 red, 4 yellow, 5 green,\n"
                "// 6 blue -- the format of icons_color.h. Keyed by OpenWeatherMap icon code.\n"
                "#ifndef __ICONS709_H__\n#define __ICONS709_H__\n\n#include <Arduino.h>\n\n")
        codes = sorted(gpre.GOOGLE_MAP)
        for code in codes:
            path = os.path.join(src, gpre.GOOGLE_MAP[code] + ".png")
            if not os.path.exists(path):
                sys.exit("missing %s -- run tools/generate_final_icons.py first, it downloads the set" % path)
            for size in ICON_SIZES:
                data = pack4(rework(path, size))
                emit_bytes(f, "ci709_%s_%d" % (code, size), data)
                total += len(data)
        f.write("\nstruct Icon709 { const char *code; const uint8_t *px220; const uint8_t *px104; };\n")
        f.write("static const Icon709 ICONS709[] = {\n")
        for code in codes:
            f.write('  {"%s", ci709_%s_220, ci709_%s_104},\n' % (code, code, code))
        f.write("};\n\n#endif\n")
    print("icons709.h: %d icons x %d sizes, %.0f KB of flash" % (len(codes), len(ICON_SIZES), total / 1024))


# ---------------------------------------------------------------- moon
MOON_PX = 72
MOON_STEPS = 32


def moon_tone(size, frac, ss=4):
    src = np.asarray(Image.open(os.path.join(HERE, "moon709", "lroc_color_poles_1k.jpg")).convert("L"),
                     dtype=np.float32) / 255.0
    hm, wm = src.shape
    near = src[hm // 8:hm - hm // 8, wm // 4:wm - wm // 4]
    lo, hi = np.percentile(near, 2), np.percentile(near, 80)
    n = size * ss
    ys, xs = np.mgrid[0:n, 0:n]
    x = (xs + 0.5) / n * 2 - 1
    y = (ys + 0.5) / n * 2 - 1
    r2 = x * x + y * y
    z = np.sqrt(np.clip(1 - r2, 0, 1))
    lat = np.arcsin(np.clip(-y, -1, 1))
    lon = np.arctan2(x, z)
    u = ((lon / (2 * math.pi) + 0.5) * wm).astype(int) % wm
    v = np.clip(((0.5 - lat / math.pi) * hm).astype(int), 0, hm - 1)
    alb = np.clip((src[v, u] - lo) / (hi - lo), 0, 1) ** 0.85
    e = 2 * math.pi * frac
    ndl = x * math.sin(e) - z * math.cos(e)
    light = np.clip(ndl * 6, 0, 1) * (0.72 + 0.28 * np.clip(ndl, 0, 1))
    tone = (0.30 + 0.70 * alb) * light
    tone[r2 > 1.0] = 0
    im = Image.fromarray((np.clip(tone, 0, 1) * 255).astype(np.uint8), "L").resize((size, size), Image.LANCZOS)
    return im


def write_moon():
    row = (MOON_PX + 7) // 8
    with open(os.path.join(OUT, "moon709.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write(NOTE)
        f.write("// The moon at %d phases, %d x %d, 1 bit per pixel, MSB first, rows padded to a\n"
                "// byte. A set bit is a WHITE pixel; everything else inside the disc is black.\n"
                "// Phase 0 is new, %d is full. Rendered from NASA's LRO colour map (public\n"
                "// domain, NASA's Scientific Visualization Studio, svs.gsfc.nasa.gov/4720).\n"
                "#ifndef __MOON709_H__\n#define __MOON709_H__\n\n#include <Arduino.h>\n\n"
                "#define MOON709_PX %d\n#define MOON709_STEPS %d\n\n"
                % (MOON_STEPS, MOON_PX, MOON_PX, MOON_STEPS // 2, MOON_PX, MOON_STEPS))
        for i in range(MOON_STEPS):
            tone = moon_tone(MOON_PX, i / float(MOON_STEPS))
            lit = np.asarray(tone.convert("1", dither=Image.Dither.FLOYDSTEINBERG)) > 0
            data = bytearray()
            for y in range(MOON_PX):
                acc = 0
                for x in range(row * 8):
                    acc = (acc << 1) | (1 if x < MOON_PX and lit[y, x] else 0)
                    if (x & 7) == 7:
                        data.append(acc)
                        acc = 0
            emit_bytes(f, "moon709_%02d" % i, bytes(data))
        f.write("\nstatic const uint8_t *const MOON709[MOON709_STEPS] = {\n")
        for i in range(MOON_STEPS):
            f.write("  moon709_%02d,\n" % i)
        f.write("};\n\n#endif\n")
    print("moon709.h: %d phases, %.0f KB of flash" % (MOON_STEPS, MOON_STEPS * row * MOON_PX / 1024))


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    want = sys.argv[1:] or ["fonts", "icons", "moon"]
    if "fonts" in want:
        write_fonts()
    if "icons" in want:
        write_icons()
    if "moon" in want:
        write_moon()
