#!/usr/bin/env python3
"""Generate the runtime font table for esp32-weather-epd.

Scans platformio/src and include for the FONT_<size>pt8b names the code
actually uses, then lib/esp32-weather-epd-assets/fonts/<Family>/ for families
that provide every one of those faces (tools/fontconvert.py generates all of
them), and writes two headers next to the families:

  fonts/font_table.h  -- includes every family whose FONT_INCLUDE_<Family>
                         macro is set (config.h), a table of their faces, and
                         the FONT_*pt8b names the renderer uses, resolved at
                         runtime through FONT_FAMILY_INDEX
  fonts/font_names.h  -- the same families' names only, for settings.cpp and
                         the portal, so they need not pull in the glyph data

Only the sizes in use go into the table, so the linker still drops the
rest: referencing all 17 faces of a family would cost ~90 KB of flash per
family for glyphs nothing draws. FreeSans is listed first (the historical
default); the rest alphabetically. Run this after adding or removing a
family, or after the renderer starts using a new size (an unknown FONT_ name
then fails to compile, which is the reminder).
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.normpath(os.path.join(HERE, "..", "platformio", "lib",
                                         "esp32-weather-epd-assets", "fonts"))
SRC_DIRS = [os.path.normpath(os.path.join(HERE, "..", "platformio", d))
            for d in ("src", "include")]
ALL_SIZES = [4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26]


def used_names():
    """FONT_<size>pt8b[_temperature] names referenced by the firmware."""
    pat = re.compile(r"FONT_([0-9]+pt8b(?:_temperature)?)\b")
    found = set()
    for d in SRC_DIRS:
        for root, _, files in os.walk(d):
            for fn in files:
                if fn.endswith((".cpp", ".h", ".inc")) and fn != "font_table.h":
                    with open(os.path.join(root, fn), encoding="utf-8",
                              errors="replace") as f:
                        found.update(pat.findall(f.read()))
    return sorted(found, key=lambda n: (n.endswith("_temperature"),
                                        int(n.split("pt")[0])))


NAMES = used_names()
if not NAMES:
    raise SystemExit("no FONT_*pt8b names found under " + ", ".join(SRC_DIRS))
HEADER = ("// Generated by tools/gen_font_table.py from the families under\n"
          "// lib/esp32-weather-epd-assets/fonts/. Do not edit: re-run the script\n"
          "// after adding a family with tools/fontconvert.py.\n")


def complete(fam):
    return all(os.path.exists(os.path.join(FONT_DIR, fam, "%s_%s.h" % (fam, n)))
               for n in NAMES)


fams = sorted(d for d in os.listdir(FONT_DIR)
              if os.path.isdir(os.path.join(FONT_DIR, d)) and complete(d))
if "FreeSans" in fams:
    fams.remove("FreeSans")
    fams.insert(0, "FreeSans")


def guard(fam):
    return "#if defined(FONT_INCLUDE_%s) && FONT_INCLUDE_%s" % (fam, fam)


out = [HEADER,
       "//",
       "// Every family whose FONT_INCLUDE_<Family> macro is set (config.h) is",
       "// compiled in and selectable at runtime through FONT_FAMILY_INDEX",
       "// (config.json \"font\", portal dropdown). Each costs roughly 150-250 KB of",
       "// flash. The FONT_*pt8b names used throughout the renderer resolve to the",
       "// selected family's face of that size.",
       "#pragma once", ""]
for fam in fams:
    out.append(guard(fam))
    for n in NAMES:
        out.append('#include "%s/%s_%s.h"' % (fam, fam, n))
    out.append("#endif")
    out.append("")
out += ["struct font_family_t",
        "{",
        "  const char *name;",
        "  // " + " ".join(NAMES),
        "  const GFXfont *const size[%d];" % len(NAMES),
        "};",
        "",
        "static const font_family_t FONT_FAMILIES[] = {"]
for fam in fams:
    out.append(guard(fam))
    faces = ", ".join("&%s_%s" % (fam, n) for n in NAMES)
    out.append('  {"%s", {%s}},' % (fam, faces))
    out.append("#endif")
out += ["};",
        "static const int FONT_FAMILY_COUNT =",
        "    sizeof(FONT_FAMILIES) / sizeof(FONT_FAMILIES[0]);",
        'static_assert(sizeof(FONT_FAMILIES) > 0,',
        '              "enable at least one FONT_INCLUDE_<Family> in config.h");',
        ""]
for i, n in enumerate(NAMES):
    out.append("#define FONT_%-20s (*FONT_FAMILIES[FONT_FAMILY_INDEX].size[%d])" % (n, i))
with open(os.path.join(FONT_DIR, "font_table.h"), "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")

out = [HEADER,
       "//",
       "// Names of the compiled-in families, in FONT_FAMILIES order (font_table.h),",
       "// for code that must not pull in the glyph data (settings.cpp, portal.cpp).",
       "#pragma once", "",
       "static const char *const FONT_FAMILY_NAMES[] = {"]
for fam in fams:
    out.append(guard(fam))
    out.append('  "%s",' % fam)
    out.append("#endif")
out += ["};",
        "static const int FONT_FAMILY_NAME_COUNT =",
        "    sizeof(FONT_FAMILY_NAMES) / sizeof(FONT_FAMILY_NAMES[0]);", ""]
with open(os.path.join(FONT_DIR, "font_names.h"), "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")

print("faces in use:", ", ".join(NAMES))
print("families:", ", ".join(fams))
print("wrote", os.path.join(FONT_DIR, "font_table.h"), "and font_names.h")
